### ISSUE TITLE
rss can not update

### ISSUE THREAD

**Issue by itplanes** [ntkme/feedbin#119]
website has update new article , but  feedbin   subscription's latest update is  two days ago

**Comment by ntkme** [comment]
Feedbin has its own heuristics on how often it checks update of a RSS feed. This is not a support channel for any issues of feedbin itself.

**Comment by itplanes** [comment]
I'm sorry, what I mean is, I use your script, and the subscription to rss and full content can be used normally after startup, but the feed has not been updated for several days. I would like to ask whether your instance is normal and whether I have built it here. What is the problem.

```
docker network create -d bridge rssnet

docker run -d \
  --name feedbin \
  --privileged \
  --hostname feedbin.testdomain.date \
  --publish 80:80/tcp \
  --publish 443:443/tcp \
  --cgroupns host \
  --network=rssnet \
  --volume /sys/fs/cgroup:/sys/fs/cgroup \
  --volume /apps/feedbin-allinone/data:/data \
  --device /dev/fuse \
  --stop-signal SIGRTMIN+3 \
  ghcr.io/ntkme/feedbin:edge
```

Domain
```
feedbin.testdomain.date
api.feedbin.testdomain.date
minio.feedbin.testdomain.date
privacy-please.feedbin.testdomain.date
```
